FROM nodered/node-red
RUN npm install node-red-contrib-yeelight
RUN npm install node-red-contrib-fritzapi
RUN npm install node-red-contrib-node-hue
# add other node red smarthome extensions you might need


