version: '3'
services:
  react_app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000

  websocket:
    build: ./emotiv_connection/nodered
    restart: unless-stopped
    ports:
      - 1880:1880
