version: '3'
services:
  nodered:
    build: docker-servers/bci-connection-nodered
    restart: unless-stopped
    ports:
      - 1880:1880

  config_server:
    build: docker-servers/smarthome-config-server
    restart: unless-stopped
    ports:
      - 5000:5000

  smarthomeplus:
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    depends_on:
      - nodered
      - config_server
