version: '3'
services:
  nodered:
    build: docker-servers/bci-connection-nodered
    restart: unless-stopped
    ports:
      - 1880:1880

  smarthomeplus:
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    depends_on:
      - nodered
