version: '3'
services:
  react_app:
    build: .
    restart: always
    ports:
      - 3000:3000

  websocket:
    build: ./emotiv_connection/websocket_server
    restart: always
    ports:
      - 4000:4000

  cortex:
    build: ./emotiv_connection/cortex_connection
    restart: always
