version: '3'
services:
  react_app:
    build: .
    restart: always
    ports:
      - 3000:3000

  nodered:
    build: ./emotiv_connection/nodered
    restart: unless-stopped
    ports:
      - 1880:1880

  smarthomeplus:
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    depends_on:
      - nodered
