version: '3'
services:
  config-server:
    build: ./smarthome-config-server
    restart: unless-stopped
    ports:
      - 5000:5000
  bci-connection:
    build: ./bci-connection-nodered
    restart: unless-stopped
    ports:
      - 1880:1880
